interface Filter {
  filterName: string;
  checkboxes: boolean;
  filterOptions: string[];
}

interface JamFilters {
  [key: string]: Filter;
}

const jamFilters: JamFilters = {
  cuisines: {
    filterName: 'CUISINE(s)',
    checkboxes: true,
    filterOptions: [
      'african',
      'asian',
      'american',
      'british',
      'cajun',
      'caribbean',
      'chinese',
      'eastern european',
      'european',
      'french',
      'german',
      'greek',
      'indian',
      'irish',
      'italian',
      'japanese',
      'jewish',
      'korean',
      'latin American',
      'mediterranean',
      'mexican',
      'middle Eastern',
      'nordic',
      'southern',
      'spanish',
      'thai',
      'vietnamese',
    ],
  },
  diets: {
    filterName: 'DIET(s)',
    checkboxes: true,
    filterOptions: [
      'gluten free',
      'ketogenic',
      'vegetatian',
      'lacto-vegetarian',
      'vegan',
      'pescetarian',
      'paleo',
      'primal',
      'low foodmap',
      'whole30',
    ],
  },
  intolerances: {
    filterName: 'INTOLERANCE(s)',
    checkboxes: true,
    filterOptions: [
      'dairy',
      'egg',
      'gluten',
      'grain',
      'peanut',
      'seafood',
      'sesame',
      'shellfish',
      'soy',
      'sulfite',
      'tree',
      'nut',
      'wheat',
    ],
  },
  'meal type': {
    filterName: 'MEAL TYPE',
    checkboxes: true,
    filterOptions: [
      'main',
      'course',
      'side dish',
      'dessert',
      'appetizer',
      'salad',
      'bread',
      'breakfast',
      'soup',
      'beverage',
      'sauce',
      'marinade',
      'fingerfood',
      'snack',
      'drink',
    ],
  },
  nutrients: {
    filterName: 'NUTRIENT(s) (per 100g)',
    checkboxes: false,
    filterOptions: [
      'calories',
      'carbs',
      'protein',
      'fat',
      'alcohol',
      'caffeine',
      'copper',
      'calcium',
      'choline',
      'cholesterol',
      'fluoride',
      'vitamin A',
      'vitamin C',
      'vitamin D',
      'vitamin E',
      'vitamin K',
      'vitamin B1',
      'vitamin B2',
      'vitamin B3',
      'vitamin B5',
      'vitamin B6',
      'vitamin B12',
      'fiber',
      'folate',
      'folic acid',
      'iodine',
      'iron',
      'magnesium',
      'manganese',
      'phosphorus',
      'potassium',
      'selenium',
      'sodium',
      'sugar',
      'zinc',
    ],
  },
};
