interface FilterType {
  id: string; // Идентификатор, который используется для key в .map и в начальном состоянии формы
  name: string; // Имя фильтра для UI
  checkboxes: boolean; // Является ли фильтр массивом для рендера чекбоксов
  options: string[]; // Опции, представленные в фильтре
}

export const jamFiltersArr: FilterType[] = [
  {
    id: 'cuisine',
    name: 'CUISINE(s)',
    checkboxes: true,
    options: [
      'african',
      'asian',
      'american',
      'british',
      'cajun',
      'caribbean',
      'chinese',
      'eastern european',
      'european',
      'french',
      'german',
      'greek',
      'indian',
      'irish',
      'italian',
      'japanese',
      'jewish',
      'korean',
      'latin american',
      'mediterranean',
      'mexican',
      'middle Eastern',
      'nordic',
      'southern',
      'spanish',
      'thai',
      'vietnamese',
    ],
  },
  {
    id: 'diet',
    name: 'DIET(s)',
    checkboxes: true,
    options: [
      'gluten free',
      'ketogenic',
      'vegetatian',
      'lacto-vegetarian',
      'vegan',
      'pescetarian',
      'paleo',
      'primal',
      'low foodmap',
      'whole30',
    ],
  },
  {
    id: 'intolerances',
    name: 'INTOLERANCE(s)',
    checkboxes: true,
    options: [
      'dairy',
      'egg',
      'gluten',
      'grain',
      'peanut',
      'seafood',
      'sesame',
      'shellfish',
      'soy',
      'sulfite',
      'tree',
      'nut',
      'wheat',
    ],
  },
  {
    id: 'type',
    name: 'MEAL TYPE',
    checkboxes: true,
    options: [
      'main',
      'course',
      'side dish',
      'dessert',
      'appetizer',
      'salad',
      'bread',
      'breakfast',
      'soup',
      'beverage',
      'sauce',
      'marinade',
      'fingerfood',
      'snack',
      'drink',
    ],
  },
  {
    id: 'nutrients',
    name: 'NUTRIENT(s) (per 100g)',
    checkboxes: false,
    options: [
      'calories',
      'carbs',
      'protein',
      'fat',
      'alcohol',
      'caffeine',
      'copper',
      'calcium',
      'choline',
      'cholesterol',
      'fluoride',
      'vitamin A',
      'vitamin C',
      'vitamin D',
      'vitamin E',
      'vitamin K',
      'vitamin B1',
      'vitamin B2',
      'vitamin B3',
      'vitamin B5',
      'vitamin B6',
      'vitamin B12',
      'fiber',
      'folate',
      'folic acid',
      'iodine',
      'iron',
      'magnesium',
      'manganese',
      'phosphorus',
      'potassium',
      'selenium',
      'sodium',
      'sugar',
      'zinc',
    ],
  },
];
